version: "3.8"

services:
  camembert-api:
    build:
      context: ./camembert-api
      dockerfile: Dockerfile
    container_name: camembert-api
    ports:
      - "7533:7533"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
      - MODEL_PATH=app/models/model.pth
